# Generated by Django 3.2.6 on 2021-10-17 07:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatar.svg', max_length=255, null=True),
        ),
    ]
