# Generated by Django 3.2.6 on 2021-10-17 09:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ds9nrbzxv/image/upload/v1634463409/gfzavj7q1wwzrw8mq8rx.svg', max_length=255, null=True),
        ),
    ]
